---
title: Análisis del Producto Interno Bruto en Mexico
author: Eduardo Jaramillo
date: '2018-07-10'
slug: análisis-del-producto-interno-bruto-en-mexico
categories: []
tags: []
header:
  caption: ''
  image: ''
---

Hay una frase que viene frecuentemente a mi cabeza cuando estás buscando una respuesta que se vuelve dificil encontrar. "Back to Basics".

Las personas generalmente tenemos opiniones acerca de lo que sucede a nuestro alrrededor y porqué sucede pero, pocas personas pueden sustentar con hechos sus opiniones para poderlos convertir en análisis serios dignos de ser leídos. 

Uno de los indicadores más utilizados por los economistas el el **Producto Interno Bruto** un indicador económico que nos ofrece una perspectiva global de lo que sucede en la economía. 

Como lo define Jonathan Heath en su libro lo que indican los indicadores, _"es la medida más comprensiva de la actividad económica de un país y, por lo mismo, el mejor indicador de su comportamiento general y del tamaño en sí de la economía"_. Un análisis profundo del comportamiento del **PIB** nos puede revelar datos que a primera vista son difíciles de notar.

Comenzamos entonces este análisis proporcionando algunas definiciones generales del indicador y sus características, así como las diferencias y coincidencias respecto a su estimación en México contra otros países. Como lo señala Jonathan Heath en su libro "Lo que indican los indicadores", _Vale la pena aclarar que no se mide absolutamente todo - PIB - y, a veces, su comportamiento puede ocultar factores importantes o engañar en cuanto al verdadero estado de salud del país_.


Gregory Makiw en su texto introductorio sobre macroeconomía dice del PIB que, _"El objetivo del PIB es resumir en una única cifra el valor monetario de la actividad económica en un determinado periodo de tiempo"_. Entonces ¿Qué es? y ¿Para qué sirve?.


Jonathan Heath lo define de la siguiente manera _"El PIB es la suma de los valores de mercado de todos los servicios y bienes finales producidos por los recursos (trabajo y capital) de la economía que residen en el país."_ osea la suma de todo lo que se produjo en un periodo de tiempo determinado que se puede vender como producto final. 

En México el Producto Interno Bruto es un indicador que genera mes con mes el INEGI con las siguientes características. 

* Producido por: INEGI
* Frecuencia: Trimestral
* Fecha de publicación: Aproximadamente 50 días después de terminar el trimestre
* Volatilidad: Moderada
* Revisión: Una vez al año (febrero)
* Dirección: Procíclico
* Tiempo: Coincidente
* Reacción de mercados: Renta fija (inversa), Renta variable (directa), Cambiario (directa)


